# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='slug',
            field=models.SlugField(default='gila', max_length=20),
            preserve_default=False,
        ),
    ]
