# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nome_disciplina', max_length=240, unique=True)),
                ('carga_horaria', models.SmallIntegerField()),
                ('teoria', models.DecimalField(decimal_places=0, max_digits=3)),
                ('pratica', models.DecimalField(decimal_places=0, max_digits=3)),
                ('ementa', models.TextField()),
                ('competencias', models.TextField()),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('conteudo', models.TextField()),
                ('bibliografia_basica', models.TextField(blank=True, null=True)),
                ('bibliografia_complementar', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DISCIPLINA',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.IntegerField(unique=True)),
                ('apelido', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=80)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'PROFESSOR',
            },
        ),
    ]
