# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_disciplina_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinaofertada',
            name='slug_disciplina',
            field=models.ForeignKey(default='tec-web', on_delete=django.db.models.deletion.CASCADE, related_name='slugDisciplina', to='cadastros.Disciplina'),
            preserve_default=False,
        ),
    ]
