# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_disciplinaofertada_slug_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinaofertada',
            name='slug_disciplina',
        ),
    ]
