# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(unique=True)),
                ('semestre', models.CharField(max_length=1, unique=True)),
                ('sigla_curso', models.ForeignKey(db_column='sigla_curso', on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.Curso')),
            ],
            options={
                'db_table': 'GRADE_CURRICULAR',
            },
        ),
    ]
