# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_gradecurricular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField(unique=True)),
                ('ano_grade', models.ForeignKey(db_column='ano_grade', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ano_periodo', to='cadastros.GradeCurricular')),
                ('semestre_grade', models.ForeignKey(db_column='semestre_grade', on_delete=django.db.models.deletion.DO_NOTHING, related_name='semestre_periodo', to='cadastros.GradeCurricular')),
                ('sigla_curso', models.ForeignKey(blank=True, db_column='sigla_curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.Curso')),
            ],
            options={
                'db_table': 'PERIODO',
            },
        ),
    ]
