# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_grade', models.ForeignKey(db_column='ano_grade', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ano_periodo_disciplina', to='cadastros.GradeCurricular')),
                ('nome_disciplina', models.ForeignKey(db_column='nome_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.Disciplina')),
                ('numero_periodo', models.ForeignKey(db_column='numero_periodo', on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.Periodo')),
                ('semestre_grade', models.ForeignKey(db_column='semestre_grade', on_delete=django.db.models.deletion.DO_NOTHING, related_name='semestre_periodo_disciplina', to='cadastros.GradeCurricular')),
                ('sigla_curso', models.ForeignKey(blank=True, db_column='sigla_curso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.Curso')),
            ],
            options={
                'db_table': 'PERIODO_DISCIPLINA',
            },
        ),
    ]
