# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_periododisciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_turma', models.CharField(max_length=1, unique=True)),
                ('ano_ofertado', models.ForeignKey(db_column='ano_ofertado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ano_turma', to='cadastros.DisciplinaOfertada')),
                ('nome_disciplina', models.ForeignKey(db_column='nome_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, related_name='nome_disciplina_turma', to='cadastros.DisciplinaOfertada')),
                ('ra_professor', models.ForeignKey(db_column='ra_professor', on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.Professor')),
                ('semestre_ofertado', models.ForeignKey(db_column='semestre_ofertado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='semestre_turma', to='cadastros.DisciplinaOfertada')),
            ],
            options={
                'db_table': 'TURMA',
            },
        ),
    ]
