# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_ofertado', models.ForeignKey(db_column='ano_ofertado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ano_ofertado_matricula', to='cadastros.DisciplinaOfertada')),
                ('id_turma', models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.Turma')),
                ('nome_disciplina', models.ForeignKey(db_column='nome_disciplina', on_delete=django.db.models.deletion.DO_NOTHING, related_name='nome_disciplina_matricula', to='cadastros.DisciplinaOfertada')),
                ('ra_aluno', models.ForeignKey(db_column='ra_aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='cadastros.Aluno')),
                ('semestre_ofertado', models.ForeignKey(db_column='semestre_ofertado', on_delete=django.db.models.deletion.DO_NOTHING, related_name='semestre_ofertado_matricula', to='cadastros.DisciplinaOfertada')),
            ],
            options={
                'db_table': 'MATRICULA',
            },
        ),
    ]
